# Generated by Django 4.2.6 on 2023-11-02 10:33
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='reference_id',
            field=models.CharField(default=uuid.uuid4().hex , max_length=32, unique=True),
        ),
    ]
