# Generated by Django 4.2.6 on 2023-11-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_is_delete_alter_category_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='reference_id',
            field=models.CharField(default='428093815f184bccbabc807e96901d6b', max_length=32, unique=True),
        ),
    ]
