# Generated by Django 4.2.6 on 2023-12-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='reference_id',
            field=models.CharField(default='848b5729131f45e69f0e3db417e78e9a', max_length=32, unique=True),
        ),
    ]
