# Generated by Django 4.2.6 on 2023-10-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=45)),
                ('otp', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'otp',
            },
        ),
    ]
