# Generated by Django 4.2.6 on 2023-12-07 16:19
import uuid


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


# def create_uuid(apps, schema_editor):
#     # Product =  apps.get_model()
#     pass


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0004_alter_category_reference_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(
                    default=uuid.uuid4().hex, max_length=32, unique=True)),
                ('color_name', models.CharField(
                    blank=True, max_length=20, null=True)),
                ('color', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(db_column='created_by',
                 on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.ForeignKey(db_column='updated_by', null=True,
                 on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'colors',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(
                    default=uuid.uuid4().hex, max_length=32, unique=True)),
                ('title', models.CharField(max_length=45)),
                ('percent', models.DecimalField(
                    decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(db_column='created_by',
                 on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.ForeignKey(db_column='updated_by', null=True,
                 on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'discount',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(
                    default=uuid.uuid4().hex, max_length=32, unique=True)),
                ('product_name', models.CharField(max_length=45)),
                ('product_code', models.CharField(max_length=15)),
                ('description', models.TextField(
                    blank=True, max_length=200, null=True)),
                ('discount', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT, related_name='+', to='product.discount')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_recommeded', models.BooleanField(default=False)),
                ('thumbnail', models.ImageField(blank=True,
                                                null=True, upload_to='uploads/product/thumbnail/')),
                ('rating', models.IntegerField(null=True)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name='+', to='category.category')),
                ('created_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(db_column='created_by',
                                                 on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.ForeignKey(db_column='updated_by', null=True,
                 on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'product',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(
                    default=uuid.uuid4().hex, max_length=32, unique=True)),
                ('tag_name', models.CharField(max_length=45)),
                ('product', models.ManyToManyField(
                    related_name='+', to='product.product')),
                ('created_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(db_column='created_by',
                 on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.ForeignKey(db_column='updated_by', null=True,
                 on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(
                    default=uuid.uuid4().hex, max_length=32, unique=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(null=True)),
                ('size_code', models.CharField(max_length=10)),
                ('size', models.CharField(max_length=10)),
                ('created_by', models.ForeignKey(db_column='created_by',
                 on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(db_column='updated_by', null=True,
                 on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'sizes',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(
                    default=uuid.uuid4().hex, max_length=32, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('color', models.ManyToManyField(
                    related_name='+', to='product.color')),
                ('product', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name='+', to='product.product')),
                ('size', models.ManyToManyField(
                    related_name='+', to='product.size')),
                ('created_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(db_column='created_by',
                 on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.ForeignKey(db_column='updated_by', null=True,
                 on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'product_attributes',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(
                    default=uuid.uuid4().hex, max_length=32, unique=True)),
                ('image', models.ImageField(null=True,
                 upload_to='uploads/product/image')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='+', to='product.productvariant')),
                ('created_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(db_column='created_by',
                 on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.ForeignKey(db_column='updated_by', null=True,
                 on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'product_image',
            },
        ),
    ]
